### ISSUE TITLE
Warning while inspecting

### ISSUE THREAD

**Issue by HexMaster101** [vatsalsinghkv/portfolio-website#1]
![Screenshot_20230226_150540](https://user-images.githubusercontent.com/110353387/221402991-794c1e05-61ee-4aa6-b9ea-1e70460b200a.png)

**Comment by HexMaster101** [comment]
Html element must have lang attribute

**Comment by vatsalsinghkv** [comment]
Feel free to make a PR

**Comment by HexMaster101** [comment]
I'm not familiar with Next.js. so please help yourself.

**Comment by vatsalsinghkv** [comment]
@HexMaster101 it's totally okey, thanks for your feedback ❤️

**Comment by vatsalsinghkv** [comment]
fixed with commit 7dfeae62494efafcd71679f3ae4f16fa1cc2499e
