### ISSUE TITLE
[FEATURE] Add lint-staged (husky) as a dev tool

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/portfolio-website#3]
### Description

Feature: Whenever we make commit it automatically runs pritter and eslint for the staged file.

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by amrishtembe1998** [comment]
Can I start working on this?

**Comment by vatsalsinghkv** [comment]
@amrishtembe1998 would you able to do it? it's not hard task but testing these tools can be little tricky. If you are really interested I will assign this issue to you. And you can join our [Discord](https://discord.gg/yZgUVDV75W) for seeking help or to discuss the issue in more depth

**Comment by shreyashchandra** [comment]
@vatsalsinghkv if it isn't done I want to work on this.

**Comment by vatsalsinghkv** [comment]
@shreyashchandra feel free to work on this ❤️
