### ISSUE TITLE
[FEATURE] Add new section for featured projects

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/portfolio-website#4]
### Description

We have a section for projects (personal). We need to add another section for showing the featured projects that can be personal and professional they should be 3-4 (max)

Steps:
- Come up with a responsive stunning UI
- Implement it
- Add it in portfolio folder

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by dfordp** [comment]
Hi can I be assigned this issue?

**Comment by Ankitmohanty2** [comment]
Assign me this issues and i want to contribute through hacktoberfest 2023.

**Comment by vatsalsinghkv** [comment]
#15
