### ISSUE TITLE
[FEATURE] Improve file structure for content

### ISSUE THREAD

**Issue by vatsalsinghkv** [vatsalsinghkv/portfolio-website#8]
### Description

Right now we have all the content in `src/lib/utils/portfolio.ts`. And its hard to manage content there. So I propose to create a `src/lib/content/` for the content of sections of the website.

- Create `src/lib/content` (If not already there).
- Move content for each section from `portfolio.ts` to new file for particular section in `content/[section].ts`.
- Fix the imports in components regarding content.

### ✨ Browser

Google Chrome

### Checklist 🚀

- [X] I checked and didn't find similar [issue](https://github.com/vatsalsinghkv/easy-fix/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/vatsalsinghkv/easy-fix/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no).

**Comment by mohdimran25** [comment]
Hi @vatsalsinghkv, I am able to help you on this :)
